services:
  - type: web
    name: fabrize-cloud-tv
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: PUBLIC_BASE_URL
        value: https://fabrize-cloud-tv.onrender.com
      - key: ADMIN_LOGIN
        value: admin
      - key: ADMIN_EMAIL
        value: your-gmail@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
