import type { Integration, IntegrationCatalogItem, IntegrationLog, IntegrationWidget, RemoteSession } from "@/types/integrations";

export const integrationCatalog: IntegrationCatalogItem[] = [
  { type: "google_sheets", name: "Google Sheets", description: "Jadval, narxlar, menyu va KPI ma'lumotlarini ekranlarga chiqarish.", category: "data", guideKey: "google_sheets" },
  { type: "telegram", name: "Telegram Channel / Bot", description: "Kanal postlari, e'lonlar va ticker xabarlarini avtomatik ko'rsatish.", category: "content", guideKey: "telegram" },
  { type: "instagram", name: "Instagram Feed / Live", description: "Business account feed, reels preview va live embed fallback.", category: "marketing", guideKey: "instagram" },
  { type: "youtube", name: "YouTube Live / Channel", description: "YouTube live URL, channel live yoki embed player.", category: "live", guideKey: "youtube" },
  { type: "weather", name: "Weather API", description: "Ob-havo widgeti: compact, fullscreen, ticker yoki card.", category: "data", guideKey: "weather" },
  { type: "rss", name: "RSS News", description: "Yangiliklar lenta, cards yoki fullscreen news ko'rinishi.", category: "content", guideKey: "rss" },
  { type: "web_url", name: "Web URL / iframe", description: "HTTPS URL, iframe, web app yoki dashboardni WebView orqali ko'rsatish.", category: "content", guideKey: "web_url" },
  { type: "anydesk", name: "AnyDesk Remote Support", description: "TV Box remote address mapping va support session ochish.", category: "remote", guideKey: "anydesk" },
  { type: "google_drive", name: "Google Drive", description: "Drive fayllari va papkalaridan media import qilishga tayyor connector.", category: "content", guideKey: "google_drive" },
  { type: "canva", name: "Canva Link", description: "Canva publish link orqali dizayn preview va WebView fallback.", category: "marketing", guideKey: "canva" },
  { type: "custom_api", name: "Custom API", description: "GET/POST endpointdan JSON olib table, cards, ticker yoki chartga map qilish.", category: "data", guideKey: "custom_api" },
  { type: "pos_webhook", name: "POS System Webhook", description: "Chegirma, price update va stock eventlari orqali widget/playlist trigger.", category: "security", guideKey: "pos_webhook" },
];

export const mockIntegrations: Integration[] = [
  {
    id: "int-google-sheets-prices",
    organizationId: "org-castmap-demo",
    type: "google_sheets",
    name: "Menu narxlari Google Sheet",
    status: "connected",
    description: "Jadvaldan menu board va price list yaratish.",
    category: "data",
    config: {
      spreadsheetId: "1CASTMAPMOCKSHEET",
      sheetName: "Menu",
      range: "A1:D20",
      refreshInterval: 300,
      displayStyle: "price_list",
      authType: "public_csv",
    },
    lastSyncAt: "2 daqiqa oldin",
    createdAt: "2026-05-28T10:00:00.000Z",
    updatedAt: "2026-05-28T10:00:00.000Z",
  },
  {
    id: "int-telegram-announcements",
    organizationId: "org-castmap-demo",
    type: "telegram",
    name: "Promo kanal e'lonlari",
    status: "connected",
    description: "Telegram kanal postlarini ticker va announcement boardga chiqarish.",
    category: "content",
    config: {
      channel: "@castmap_demo",
      contentType: "announcement",
      refreshMode: "webhook",
      moderation: "auto_publish",
    },
    credentials: { botToken: "****:masked" },
    lastSyncAt: "5 daqiqa oldin",
  },
  {
    id: "int-anydesk-support",
    organizationId: "org-castmap-demo",
    type: "anydesk",
    name: "TV Box remote support",
    status: "connected",
    description: "AnyDesk address mapping va remote session linklari.",
    category: "remote",
    config: {
      licenseId: "AD-CASTMAP-DEMO",
      namespace: "castmap",
      deviceMappings: [{ deviceId: "device-kj8aha-mpgpx88j", address: "123 456 789" }],
    },
    credentials: { apiPassword: "********" },
    lastSyncAt: "1 soat oldin",
  },
  {
    id: "int-weather-tashkent",
    organizationId: "org-castmap-demo",
    type: "weather",
    name: "Toshkent ob-havo",
    status: "connected",
    description: "Toshkent uchun compact weather widget.",
    category: "data",
    config: { city: "Toshkent", language: "uz", unit: "celsius", displayStyle: "card", refreshInterval: 900 },
    lastSyncAt: "15 daqiqa oldin",
  },
  {
    id: "int-instagram-feed",
    organizationId: "org-castmap-demo",
    type: "instagram",
    name: "Instagram social wall",
    status: "requires_auth",
    description: "Meta OAuth kerak, mock feed preview tayyor.",
    category: "marketing",
    config: { accountId: "17841400000000000", displayStyle: "feed_grid" },
    lastError: "OAuth access token ulanmagan",
  },
  {
    id: "int-youtube-live",
    organizationId: "org-castmap-demo",
    type: "youtube",
    name: "YouTube Live ekran",
    status: "disconnected",
    description: "YouTube live yoki channel URL orqali WebView/HLS.",
    category: "live",
    config: { url: "https://www.youtube.com/@castmap/live", autoplay: true, mute: true },
  },
  {
    id: "int-rss-news",
    organizationId: "org-castmap-demo",
    type: "rss",
    name: "Yangiliklar RSS",
    status: "error",
    description: "RSS ticker uchun yangiliklar.",
    category: "content",
    config: { url: "https://example.com/rss.xml", count: 5, displayStyle: "ticker" },
    lastError: "RSS URL mock rejimda tekshirildi",
  },
  {
    id: "int-web-dashboard",
    organizationId: "org-castmap-demo",
    type: "web_url",
    name: "Web URL dashboard",
    status: "connected",
    description: "HTTPS sahifani fullscreen WebView orqali chiqarish.",
    category: "content",
    config: { url: "https://castmap.uz", displayMode: "fullscreen", refreshInterval: 600, zoom: 1 },
    lastSyncAt: "Hozir",
  },
];

export const mockIntegrationWidgets: IntegrationWidget[] = [
  {
    id: "widget-google-sheets-price-list",
    organizationId: "org-castmap-demo",
    integrationId: "int-google-sheets-prices",
    name: "Burger menu price list",
    type: "google_sheets",
    status: "active",
    config: { displayStyle: "price_list", layout: "fullscreen", duration: 20, refreshInterval: 300 },
    previewData: {
      columns: ["Product", "Price", "Discount", "Status"],
      rows: [["Burger Menu", "45000", "20%", "Active"], ["Lavash Set", "39000", "10%", "Active"]],
    },
  },
  {
    id: "widget-telegram-ticker",
    organizationId: "org-castmap-demo",
    integrationId: "int-telegram-announcements",
    name: "Telegram e'lon ticker",
    type: "telegram",
    status: "active",
    config: { displayStyle: "ticker", layout: "bottom_ticker", duration: 15, refreshInterval: 120 },
    previewData: { messages: ["Bugun barcha filiallarda yangi aksiya", "Kechki chegirma 20:00 gacha davom etadi"] },
  },
  {
    id: "widget-weather-card",
    organizationId: "org-castmap-demo",
    integrationId: "int-weather-tashkent",
    name: "Toshkent ob-havo card",
    type: "weather",
    status: "active",
    config: { displayStyle: "card", layout: "right_panel", duration: 12, refreshInterval: 900 },
    previewData: { city: "Toshkent", temp: 27, condition: "Quyoshli", humidity: 34 },
  },
];

export const mockIntegrationLogs: IntegrationLog[] = [
  { id: "ilog-1", integrationId: "int-google-sheets-prices", level: "success", message: "Google Sheets mock data synced", createdAt: "2026-05-29T09:00:00.000Z" },
  { id: "ilog-2", integrationId: "int-telegram-announcements", level: "info", message: "Telegram webhook endpoint tayyor", createdAt: "2026-05-29T09:03:00.000Z" },
  { id: "ilog-3", integrationId: "int-rss-news", level: "warning", message: "RSS mock mode ishlatilmoqda", createdAt: "2026-05-29T09:05:00.000Z" },
];

export const mockRemoteSessions: RemoteSession[] = [
  {
    id: "remote-anydesk-demo",
    deviceId: "device-kj8aha-mpgpx88j",
    provider: "anydesk",
    remoteAddress: "123 456 789",
    sessionUrl: "anydesk:123456789",
    status: "pending",
    createdAt: "2026-05-29T09:10:00.000Z",
  },
];
